let list = [
{"id": 3,"artist": "rich brian","title": "history","year": 2018,"genre": "rap","date": "01:00:00","link": "history.html"}, 
{"id": 4,"artist": "rich brian","title": "crisis","year": 2018,"genre": "rap","date": "01:10:00","link": "crisiss.html"}, 
{"id": 5,"artist": "rich brian","title": "glow like that","year": 2018,"genre": "rap","date": "01:20:00","link": "glow.html"}, 
{"id": 6,"artist": "rich brian","title": "attention","year": 2018,"genre": "rap","date": "04:30:21","link": "attention.html"},
{"id": 50,"artist": "why dont we","title": "trust fund baby","year": 2018,"genre": "rock","date": "08:59:59","link": "trust fund.html"}, 
{"id": 51,"artist": "rich brian","title": "trespass","year": 2018,"genre": "rap","date": "09:00:00","link": "trespass.html"}, 
{"id": 55,"artist": "rich brian","title": "dat stick","year": 2018,"genre": "rap","date": "01:21:04","link": "dat stick.html"}, 
{"id": 53,"artist": "Bebe Rexha","title": "I am a mess","year": 2018,"genre": "rock","date": "01:16:19","link": "I am.html"}, 
{"id": 56,"artist": "Selena Gomez","title": "back to you","year": 2018,"genre": "edm","date": "01:22:51","link": "back to.html"}, 
{"id": 57,"artist": "Alan Walker","title": "darkside","year": 2018,"genre": "edm","date": "01:23:25","link": "darkside.html"}, 
{"id": 58,"artist": "Charlie puth","title": "done for me","year": 2018,"genre": "pop","date": "01:25:15","link": "done for.html"}, 
{"id": 59,"artist": "nick jonas","title": "right now","year": 2018,"genre": "pop","date": "01:30:21","link": "right now.mht"}, 
{"id": 60,"artist": "the vamps","title": "just my type","year": 2018,"genre": "pop","date": "01:31:27","link": "Just my.mht"}, 
{"id": 61,"artist": "Alan Walker","title": "diamond heart","year": 2018,"genre": "edm","date": "01:32:10","link": "Diamond.mht"}, 
{"id": 62,"artist": "Anne Marie","title": "rockabye","year": 2017,"genre": "rnb","date": "01:35:09","link": "Rockbye.mht"}, 
{"id": 63,"artist": "clean bandit","title": "baby","year": 2018,"genre": "pop-edm","date": "01:37:22","link": "Baby.mht"}, 
{"id": 64,"artist": "mø","title": "blur","year": 2018,"genre": "edm","date": "01:37:48","link": "blur.mht"}, 
{"id": 65,"artist": "Alan Walker","title": "lily","year": 2019,"genre": "edm","date": "01:40:16","link": "Lily.mht"}, 
{"id": 66,"artist": "Ellie Goulding","title": "close to me","year": 2019,"genre": "pop-edm","date": "01:42:16","link": "close.mht"}, 
{"id": 67,"artist": "unknown brain","title": "why do i","year": 2018,"genre": "ncs","date": "01:47:17","link": "whyd.mht"}, 
{"id": 68,"artist": "Sabrina Carpenter","title": "why","year": 2019,"genre": "pop","date": "01:48:09","link": "why.mht"}, 
{"id": 69,"artist": "imagine dragons","title": "whatever it takes","year": 2017,"genre": "rock","date": "01:51:27","link": "what.mht"}, 
{"id": 70,"artist": "the Chainsmokers","title": "hope","year": 2019,"genre": "edm","date": "01:52:24","link": "hope.mht"}, 
{"id": 71,"artist": "Eminem","title": "rap god","year": 2018,"genre": "rap","date": "01:53:01","link": "rap.mht"}, 
{"id": 72,"artist": "Selena Gomez","title": "it ain\'t me","year": 2018,"genre": "edm","date": "01:57:19","link": "it aint.mht"}, 
{"id": 73,"artist": "cardi b","title": "I like it","year": 2019,"genre": "rnb","date": "02:00:28","link": "like it.mht"}, 
{"id": 74,"artist": "post Malone","title": "rockstar","year": 2018,"genre": "rnb","date": "02:02:00","link": "rockstar.mht"}, 
{"id": 76,"artist": "imagine dragons","title": "natural","year": 2014,"genre": "rock","date": "02:03:00","link": "natural.mht"}, 
{"id": 78,"artist": "Nick Jones","title": "new light","year": 2018,"genre": "pop","date": "02:04:00","link": "nlight.mht"}, 
{"id": 79,"artist": "little mix","title": "only you","year": 2017,"genre": "edm","date": "10:25:23","link": "only you.html"}, 
{"id": 80,"artist": "halsey","title": "without me","year": 2019,"genre": "edm","date": "10:27:07","link": "without.mht"}, 
{"id": 81,"artist": "the Chainsmokers","title": "owe me","year": 2019,"genre": "edm","date": "10:27:47","link": "owe.mht"}, 
{"id": 82,"artist": "dua lipa","title": "be the one","year": 2018,"genre": "edm","date": "10:29:57","link": "one.mht"}, 
{"id": 83,"artist": "rich brian","title": "watch out","year": 2018,"genre": "rap","date": "10:30:25","link": "watch.mht"}, 
{"id": 84,"artist": "unknown brain","title": "inspirations","year": 2019,"genre": "ncs","date": "10:32:03","link": "inspiration.mht"}, 
{"id": 85,"artist": "bts","title": "boy with luv","year": 2019,"genre": "k-pop","date": "10:33:48","link": "luv.mht"}, 
{"id": 86,"artist": "Billie elish","title": "bad guy","year": 2019,"genre": "pop","date": "10:34:51","link": "badguy.mht"}, 
{"id": 87,"artist": "Vincent","title": "show me","year": 2019,"genre": "edm","date": "10:36:03","link": "show.mht"}, 
{"id": 88,"artist": "rich brian","title": "yellow","year": 2019,"genre": "rnb","date": "10:37:06","link": "yellow.mht"}, 
{"id": 89,"artist": "Billie elish","title": "lovely","year": 2019,"genre": "pop","date": "10:37:53","link": "lovely.mht"}, 
{"id": 90,"artist": "skinnyfabs","title": "happy","year": 2019,"genre": "pop","date": "10:38:26","link": "happy.mht"}, 
{"id": 91,"artist": "slippydoor","title": "give it up","year": 2019,"genre": "rap","date": "10:39:56","link": "giveit.mht"}, 
{"id": 92,"artist": "Billie elish","title": "bad guy","year": 2019,"genre": "pop-edm","date": "10:40:59","link": "bad.mht"}, 
{"id": 93,"artist": "Sabrina Carpenter","title": "in my bed","year": 2019,"genre": "pop-edm","date": "10:42:36","link": "bed.mht"}, 
{"id": 94,"artist": "rich brian","title": "rapapapa","year": 2019,"genre": "rap","date": "10:44:09","link": "rapa.mht"}, 
{"id": 95,"artist": "rich brian","title": "100 degrees","year": 2019,"genre": "rnb","date": "10:44:43","link": "100.mht"}, 
{"id": 96,"artist": "the Chainsmokers","title": "take away","year": 2019,"genre": "edm","date": "10:45:50","link": "takeaway.mht"}, 
{"id": 97,"artist": "Anne Marie","title": "ciao adios","year": 2017,"genre": "pop","date": "10:46:54","link": "adios.mht"}, 
{"id": 98,"artist": "eevnxx","title": "toxic","year": 2019,"genre": "rap","date": "10:47:55","link": "toxic.mht"}, 
{"id": 99,"artist": "21 Pillots","title": "ride","year": 2016,"genre": "pop-edm","date": "10:48:43","link": "ride.mht"}, 
{"id": 100,"artist": "Sabrina Carpenter","title": "why","year": 2019,"genre": "pop","date": "10:49:26","link": "why.mht"}, 
{"id": 101,"artist": "Connor maynard","title": "are you sure","year": 2019,"genre": "pop-edm","date": "10:51:31","link": "areyou.mht"}, 
{"id": 102,"artist": "lil nas x","title": "old town road","year": 2019,"genre": "rnb","date": "10:52:40","link": "town.mht"}, 
{"id": 103,"artist": "bts","title": "chiken noddle soup","year": 2019,"genre": "k-pop","date": "10:53:25","link": "chick.mht"}, 
{"id": 104,"artist": "addele","title": "set fire to the rain","year": 2016,"genre": "pop","date": "10:56:54","link": "setfire.mht"}, 
{"id": 105,"artist": "sia","title": "cheapthrills","year": 2016,"genre": "rnb","date": "10:57:36","link": "cheap.mht"}, 
{"id": 106,"artist": "Jonas brothers","title": "only human","year": 2019,"genre": "pop","date": "10:58:25","link": "human.mht"}, 
{"id": 107,"artist": "lenka","title": "trouble is a friend","year": 2016,"genre": "pop","date": "10:59:25","link": "trouble.mht"}, 
{"id": 108,"artist": "Camilla cabello","title": "liar","year": 2019,"genre": "pop","date": "11:00:29","link": "liar.mht"}, 
{"id": 109,"artist": "zara Larson","title": "uncover","year": 2016,"genre": "edm","date": "11:01:11","link": "uncover.mht"}
]

let genres =[
		{genre:"edm",desc:"Electronic music dance",img:"images.jpeg-11.jpg"},
		{genre:"pop",desc:"popular music",img:"images.jpeg-8.jpg"},
		{genre:"k-pop",desc:"korean popular",img:"images.jpeg-16.jpg"},
		{genre:"pop-edm",desc:"pop electronic music dance",img:"images.jpeg-12.jpg"},
		{genre:"rnb",desc:"rhythm and blues",img:"images.jpeg-14.jpg"},
		{genre:"rock",desc:"rock music",img:"images.jpeg-9.jpg"},
		{genre:"rap",desc:"mumbled & lyrics song",img:"images.jpeg-15.jpg"}			
		]